version: '3.7'

volumes:
  db_data:

x-shared_environment: &shared_environment
  SPRING_PROFILES_ACTIVE: production
  DATABASE_HOST: db
  DATABASE_NAME: blog
  DATABASE_USERNAME: blog
  DATABASE_PASSWORD: abc123

services:
  app:
    image: springboot-app:latest
    build:
      context: .
    environment:
      <<: *shared_environment
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog
    depends_on:
      - db
    ports:
      - '8080:8080'
    command: ["./mvnw", "spring-boot:run"]

  db:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: blog
    ports:
      - '5432:5432'

  test_db:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: blog_test
    ports:
      - '5433:5432'

  cache:
    image: redis:alpine
    container_name: blog_cache
    ports:
      - '6379:6379'